name: Code Quality

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  code-quality:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-code-quality.yml@main
    with:
      php: 8.1
